import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

const primaryFont = Open_Sans({
  weight: "600",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pepi Pepi's playground ❤️",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${primaryFont.className} antialiased`}>
        <main>{children}</main>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
