import React from 'react';
import type { Metadata } from 'next';
import { publicSans } from '@/styles/fonts';
import '../globals.css';

export const metadata: Metadata = {
    title: "Pepi Pepi's playground ❤️",
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${publicSans.className} antialiased`}>{children}</div>
    );
}
