import React from 'react';
import type { Metadata } from 'next';
import '../globals.css';
import { primaryFont } from '@/styles/fonts';

export const metadata: Metadata = {
    title: "Pepi Pepi's playground ❤️",
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${primaryFont.className} antialiased`}>{children}</div>
    );
}
